package com.inflotrolix.mvp.security.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.inflotrolix.mvp.security.configuration.AuthClientDetailsConverter;
import com.inflotrolix.mvp.security.enums.Authorities;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.time.Instant;
import java.util.*;

@DynamoDBTable(tableName = "dynamoDbRule2")
public class User {
//        implements UserDetails {


    private String PKey;

    private String SortKey;

    private String username;

    private String password;

    private AuthClientDetails clientDetails;
//
//    private String firstname;
//
//    private String lastName;
//
//    private Instant birthDate;
//
//    private String address;
//
//    private boolean activated;
//
//    private String activationKey;
//
//    private String resetPasswordKey;
//
//    private Set<Authorities> authorities = new HashSet<>();
//
//
    @DynamoDBHashKey(attributeName = "PKey")
    @DynamoDBAutoGeneratedKey
    public String getPKey() {
        return PKey;
    }

    public void setPKey(String PKey) {
        this.PKey = PKey;
    }

    @DynamoDBRangeKey(attributeName = "SortKey")
    public String getSortKey() {
        return SortKey;
    }

    public void setSortKey(String sortKey) {
        SortKey = sortKey;
    }

    @DynamoDBAttribute(attributeName = "credentials")
    @DynamoDBTypeConverted(converter = AuthClientDetailsConverter.class)
    public AuthClientDetails getClientDetails() {
        return clientDetails;
    }

    public void setClientDetails(AuthClientDetails clientDetails) {
        this.clientDetails = clientDetails;
    }

    //
//    @DynamoDBAttribute(attributeName = "firstName")
//    public String getFirstname() {
//        return firstname;
//    }
//
//    public void setFirstname(String firstname) {
//        this.firstname = firstname;
//    }
//
//
//    @DynamoDBAttribute(attributeName = "lastName")
//    public String getLastName() {
//        return lastName;
//    }
//
//    public void setLastName(String lastName) {
//        this.lastName = lastName;
//    }
//
//    @DynamoDBAttribute(attributeName = "birthDate")
//    public Instant getBirthDate() {
//        return birthDate;
//    }
//
//    public void setBirthDate(Instant birthDate) {
//        this.birthDate = birthDate;
//    }
//
//    @DynamoDBAttribute(attributeName = "address")
//    public String getAddress() {
//        return address;
//    }
//
//    public void setAddress(String address) {
//        this.address = address;
//    }

    @DynamoDBAttribute(attributeName = "password")
    public String getPassword() {
        return password;
    }

    @DynamoDBAttribute(attributeName = "username")
    public String getUsername() {
        return username;
    }

//    @DynamoDBAttribute(attributeName = "authorities")
//    @Override
//    public List<GrantedAuthority> getAuthorities() {
//        return new ArrayList<>(authorities);
//    }
//
    public void setUsername(String username) {
        this.username = username;
    }

    public void setPassword(String password) {
        this.password = password;
    }
//
//    @Override
//    public boolean isAccountNonExpired() {
//        return true;
//    }
//
//    @Override
//    public boolean isAccountNonLocked() {
//        return true;
//    }
//
//    @Override
//    public boolean isCredentialsNonExpired() {
//        return true;
//    }
//
//    @Override
//    public boolean isEnabled() {
//        return activated;
//    }
//
//    public boolean isActivated() {
//        return activated;
//    }
//
//    public void setActivated(boolean activated) {
//        this.activated = activated;
//    }
//
//    public String getActivationKey() {
//        return activationKey;
//    }
//
//    public void setActivationKey(String activationKey) {
//        this.activationKey = activationKey;
//    }
//
//    public String getResetPasswordKey() {
//        return resetPasswordKey;
//    }
//
//    public void setResetPasswordKey(String resetPasswordKey) {
//        this.resetPasswordKey = resetPasswordKey;
//    }
//
//    public void setAuthorities(Set<Authorities> authorities) {
//        this.authorities = authorities;
//    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        User user = (User) o;
        return Objects.equals(PKey, user.PKey);
    }

    @Override
    public int hashCode() {
        return Objects.hash(PKey);
    }

}
